version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: jreg-azurite
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"

volumes:
  azurite-data:
