spring:
  application:
    name: jreg

aws:
  s3:
    bucket-name: jreg-registry
    endpoint-override: http://localhost:4566
    region: us-east-1

logging:
  level:
    com.jreg: DEBUG
    software.amazon.awssdk.services.s3: WARN
