spring:
  application:
    name: jreg
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: false
    pathmatch:
      matching-strategy: ant_path_matcher
    log-resolved-exception: true

server:
  port: 5000
  forward-headers-strategy: framework

azure:
  storage:
    container-name: jreg-registry
    endpoint: https://${AZURE_STORAGE_ACCOUNT_NAME:jreg}.blob.core.windows.net

logging:
  level:
    root: INFO
    com.jreg: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  prometheus.metrics.export.enabled: true
